[bowser]
dry_run = true

[[bowser.backends]]
kind = "AWS-S3"
region = "eu-west-1"
access_key_id = "access key"
secret_access_key = "secret squirrel stuff"

[[bowser.backends.buckets]]
name = "a literal bucket"
prefix = "some/root/prefix"

[bowser.backends.buckets.link]
target = {kind="RegexMatch", pattern='\d{8}T\d{6}'}
name = "latest"