use crate::Result;
use config::Config;
use sec::Secret;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use xdg::BaseDirectories;

const BOWSER_DRY_RUN: &str = "bowser.dry_run";

pub(crate) fn config_root() -> PathBuf {
    let base = BaseDirectories::new();
    base.config_home
        .expect("Could not find home directory: is $HOME not set?")
}

#[derive(Default)]
pub(crate) struct ConfigOverrides {
    pub dry_run: Option<bool>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub(crate) struct AppConfig {
    pub(crate) bowser: BowserConfig,
}

impl AppConfig {
    fn parser(sources: &[PathBuf], overrides: ConfigOverrides) -> Result<Config> {
        let mut builder = Config::builder();
        for source in sources {
            builder = builder
                .add_source(config::File::with_name(source.to_str().unwrap()).required(false));
        }

        Ok(builder
            .set_override_option(BOWSER_DRY_RUN, overrides.dry_run)?
            .build()?)
    }

    pub fn try_load(
        from: Option<Vec<PathBuf>>,
        overrides: Option<ConfigOverrides>,
    ) -> Result<AppConfig> {
        let sources = from.unwrap_or_else(|| {
            let config_root = config_root();
            vec![
                PathBuf::from("/etc/bowser/config.toml"),
                PathBuf::from(config_root.join("bowser/config.toml").to_str().unwrap()),
            ]
        });
        let overrides = overrides.unwrap_or_default();
        let parser = AppConfig::parser(&sources, overrides)?;
        Ok(parser.try_deserialize()?)
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub(crate) struct BowserConfig {
    /// If `true` then output what work would be done without actually doing it.
    pub(crate) dry_run: Option<bool>,
    pub(crate) backends: Vec<BackendConfig>,
    /// A set of .gitignore-style patterns that should be ignored during upload.
    /// By default, all Bowser sentinel files are ignored (.bowser.*).
    pub(crate) ignore: Option<Vec<String>>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub(crate) enum BackendConfig {
    #[serde(rename = "AWS-S3")]
    AwsS3 {
        region: String,
        access_key_id: Secret<String>,
        secret_access_key: Secret<String>,
        buckets: Vec<Bucket>,
    },
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub(crate) struct Bucket {
    /// The target bucket name.
    pub(crate) name: String,
    /// The root prefix objects should be uploaded under.
    ///
    /// The default value is "" (the empty string) which means content will be sync'd
    /// directly to the top-level of the given bucket name.
    ///
    /// If prefix is not empty, then content will be sync'd under the provided prefix.
    pub(crate) prefix: Option<String>,
}

impl Bucket {
    /// Join this bucket's prefix field, if present, with the prefix argument.
    ///
    /// This has the effect of creating an "absolute path" or key under this Bucket.
    ///
    /// Joining is done by treating both this bucket's prefix and the prefix argument
    /// as path parts. If the two parts cannot be sensibly joined together like path parts
    /// then this can fail.
    pub(crate) fn join_prefix(&self, prefix: impl Into<String>) -> Result<String> {
        let root = self.prefix.clone().unwrap_or("/".to_string());
        let as_path = PathBuf::from(root)
            .join(prefix.into())
            .into_os_string()
            .into_string()?;
        let result = as_path
            .strip_prefix("/")
            .map(String::from)
            .unwrap_or(as_path);
        Ok(result)
    }
}

///////////////////////////////////// Generated by Claude Opus 4.5 /////////////////////////////////

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    fn write_config_file(content: &str) -> NamedTempFile {
        let mut file = NamedTempFile::with_suffix(".toml").unwrap();
        write!(file, "{}", content).unwrap();
        file
    }

    #[test]
    fn test_try_load_from_custom_path() {
        let config_content = r#"
[bowser]
dry_run = false

[[bowser.backends]]
kind = "AWS-S3"
region = "us-east-1"
access_key_id = "test-key"
secret_access_key = "test-secret"

[[bowser.backends.buckets]]
name = "test-bucket"
"#;
        let config_file = write_config_file(config_content);
        let sources = vec![PathBuf::from(config_file.path())];

        let result = AppConfig::try_load(Some(sources), None);
        assert!(result.is_ok());

        let config = result.unwrap();
        assert_eq!(config.bowser.dry_run, Some(false));
        assert_eq!(config.bowser.backends.len(), 1);
    }

    #[test]
    fn test_try_load_with_dry_run_override() {
        let config_content = r#"
[bowser]
dry_run = false

[[bowser.backends]]
kind = "AWS-S3"
region = "us-east-1"
access_key_id = "test-key"
secret_access_key = "test-secret"

[[bowser.backends.buckets]]
name = "test-bucket"
"#;
        let config_file = write_config_file(config_content);
        let sources = vec![PathBuf::from(config_file.path())];
        let overrides = ConfigOverrides {
            dry_run: Some(true),
        };

        let result = AppConfig::try_load(Some(sources), Some(overrides));
        assert!(result.is_ok());

        let config = result.unwrap();
        // Override should take precedence over file value
        assert_eq!(config.bowser.dry_run, Some(true));
    }

    #[test]
    fn test_try_load_missing_required_fields() {
        let config_content = r#"
[bowser]
dry_run = true
"#;
        let config_file = write_config_file(config_content);
        let sources = vec![PathBuf::from(config_file.path())];
        let result = AppConfig::try_load(Some(sources), None);
        assert!(result.is_err());
    }

    #[test]
    fn test_try_load_nonexistent_file() {
        let sources = vec![PathBuf::from("/nonexistent/path/config.toml")];
        let result = AppConfig::try_load(Some(sources), None);
        assert!(result.is_err());
    }

    #[test]
    fn test_try_load_no_sources() {
        // Simulates what happens when the default config files don't exist.
        // Since sources are marked .required(false), the parser succeeds but
        // deserialization fails due to missing required fields.
        let sources: Vec<PathBuf> = vec![];
        let result = AppConfig::try_load(Some(sources), None);
        assert!(result.is_err());
    }

    #[test]
    fn test_config_overrides_default() {
        let overrides = ConfigOverrides::default();
        assert_eq!(overrides.dry_run, None);
    }

    #[test]
    fn test_try_load_with_ignore_patterns() {
        let config_content = r#"
[bowser]
dry_run = false
ignore = ["*.log", "temp/*"]

[[bowser.backends]]
kind = "AWS-S3"
region = "us-east-1"
access_key_id = "test-key"
secret_access_key = "test-secret"

[[bowser.backends.buckets]]
name = "test-bucket"
"#;
        let config_file = write_config_file(config_content);
        let sources = vec![PathBuf::from(config_file.path())];

        let result = AppConfig::try_load(Some(sources), None);
        assert!(result.is_ok());

        let config = result.unwrap();
        let ignore = config.bowser.ignore.unwrap();
        assert_eq!(ignore.len(), 2);
        assert!(ignore.contains(&"*.log".to_string()));
        assert!(ignore.contains(&"temp/*".to_string()));
    }

    #[test]
    fn test_try_load_multiple_backends() {
        let config_content = r#"
[bowser]
dry_run = false

[[bowser.backends]]
kind = "AWS-S3"
region = "us-east-1"
access_key_id = "key1"
secret_access_key = "secret1"

[[bowser.backends.buckets]]
name = "bucket1"

[[bowser.backends]]
kind = "AWS-S3"
region = "us-west-2"
access_key_id = "key2"
secret_access_key = "secret2"

[[bowser.backends.buckets]]
name = "bucket2"
prefix = "data/"
"#;
        let config_file = write_config_file(config_content);
        let sources = vec![PathBuf::from(config_file.path())];

        let result = AppConfig::try_load(Some(sources), None);
        assert!(result.is_ok());

        let config = result.unwrap();
        assert_eq!(config.bowser.backends.len(), 2);
    }
}

//////////////////////////////////////// End Generated Code ////////////////////////////////////////
