name: AI Code Review
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  AICodeReview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    continue-on-error: true
    permissions:
      contents: read
      pull-requests: write
    container:
      image: registry.gitlab.com/redhat/edge/ci-cd/ai-code-review:latest
    steps:
      - name: Run AI Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |-
          ai-code-review --ai-provider anthropic \
                         --ai-model claude-sonnet-4-5 \
                         --pr-number ${{ github.event.pull_request.number }} \
                         --post
